export const FETCH_PEOPLE_REQUEST = 'fetch people request'
export const FETCH_PEOPLE_SUCCESS = 'fetch people success'
export const SAVE_PEOPLE_REQUEST = 'save people request'
export const SAVE_PEOPLE_SUCCESS = 'save people success'
export const SAVE_PEOPLE_ERROR = 'save people error'